### ISSUE TITLE
Add precision for Error message

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/SimSwap#44]
**Problem description**
We are a bit vague on some error message - we probably need to be more explicit - like for OTP.

**Possible evolution**
Add more error definition:
```
          PhoneNumberNotAllowed:
              value:
                status: 403
                code: SIMSWAP.PHONE_NUMBER_NOT_IN_OPERATOR_SCOPE
                message: SI Swap can't be checked because this number is not managed by operator.
```

@monamok @DT-DawidWroblewski  WDYT ?
