### ISSUE TITLE
PhoneNumber pattern - clarification on optional "+" prefix

### ISSUE THREAD

**Issue by trehman-gsma** [camaraproject/SimSwap#85]
I am seeking clarification on the phone number pattern in the [current spec](https://github.com/camaraproject/SimSwap/blob/main/code/API_definitions/sim_swap.yaml). This is the schema: 

```
    PhoneNumber:
      type: string
      pattern: '^\+?[0-9]{5,15}$'
      example: '+346661113334'
      description: Subscriber number in E.164 format (starting with country code). Optionally prefixed with '+'.
```

Regarding the "+" prefix:
* Is the expectation that Operators **must** support both a phone number containing a "+" and support a phone number without a "+" prefix?
* Or is it the operator choice to support either combination? 

To elaborate, please see this table that represents the options of supporting a prefix. Are all options valid?

||Operator supports number with a "+" prefix|Operator supports number without a "+" prefix  |
|--|--|--|
| Option 1| Y | Y |
| Option 2| Y | N |
| Option 3| N | Y |
